[build]
  # Directory to publish
  publish = "dist"
  
  # Build command
  command = "npm run build"

[build.environment]
  # Node version
  NODE_VERSION = "18"

[[redirects]]
  # Redirect all routes to index.html for client-side routing
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
[[headers]]
  # Cache static assets
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
